spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:banking}?currentSchema=${POSTGRES_SCHEMA:currency}
    username: ${POSTGRES_USERNAME:antoha}
    password: ${POSTGRES_PASSWORD:antoha}
  liquibase:
    default-schema: ${POSTGRES_SCHEMA:currency}
    change-log: db/changelog/db.changelog.yaml
    liquibase-schema: ${POSTGRES_SCHEMA:currency}
  rabbitmq:
    port: 5672
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA:currency}
        format_sql: true

clevertec:
  rabbit:
    queue:
      currency: currency

logging:
  level:
    org:
      hibernate:
        type: trace
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
