server:
  port: 8083
spring:
  application:
    name: CURRENCY-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  liquibase:
    default-schema: ${POSTGRES_SCHEMA}
    change-log: db/changelog/db.changelog.yaml
    liquibase-schema: ${POSTGRES_SCHEMA}
  jpa:
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA}
    hibernate:
      ddl-auto: validate
  web:
    resources:
      add-mappings: false
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false


