spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_schema: auth
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    default-schema: auth
    liquibase-schema: auth
  datasource:
    url: jdbc:postgresql://localhost:15432/clevertec-banking?currentSchema=auth
    username: clevertec
    password: banking
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
#logging:
#  config: #мб уйдет в стартер