server:
  port: ${PORT}
spring:
  application:
    name: AUTH-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DEFAULT_SCHEMA}
    database: postgresql
token:
  secret-key: ${JWT_SECRET}
  refresh-token-expiration-ms: 604800000 # 1 неделя в миллисекундах
  token-expiration-ms: 604800000 # 2 минуты = 120000 в миллисекундах
