spring:
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    default-schema: ${DEFAULT_SCHEMA}
    liquibase-schema: ${DEFAULT_SCHEMA}
  datasource:
    url: jdbc:postgresql://localhost:${DEV_DB_PORT}/${DB_NAME}?currentSchema=${DEFAULT_SCHEMA}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
eureka:
  client:
    service-url:
      defaultZone: http://${DEV_EUREKA_HOST}:${EUREKA_PORT}/eureka/
#logging:
#  config: #мб уйдет в стартер