version: '3.8'
services:
  eureka-server:
    image: eureka-server:0.0.1
    build:
      context: ./eureka-server/
      dockerfile: /Dockerfile
    restart: always
    ports:
      - "8761:8761"
    networks:
      - clevertec-banking-net

  api-gateway:
    image: api-gateway:0.0.1
    build:
      context: ./api-gateway/
      dockerfile: /Dockerfile
    restart: always
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - ./api-gateway/.env
    ports:
      - "8080:8080"
    networks:
      - clevertec-banking-net

  service-db:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: clevertec
      POSTGRES_PASSWORD: banking
      POSTGRES_DB: clevertec-banking
    ports:
      - "15432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - clevertec-banking-net

  auth-service:
    image: auth-service:0.0.1
    build:
      context: ./auth-service
      dockerfile: /Dockerfile
    restart: always
    depends_on:
      - service-db
      - eureka-server
      - api-gateway
    ports:
      - "9191:9191"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://service-db/clevertec-banking
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - ./auth-service/.env
    networks:
      - clevertec-banking-net

  customer-service:
    image: customer-service:0.0.1
    build:
      context: ./customer-service
      dockerfile: /Dockerfile
    restart: always
    depends_on:
      - service-db
      - eureka-server
      - api-gateway
    ports:
      - "8082:8082"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://service-db/clevertec-banking
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - ./customer-service/.env
    networks:
      - clevertec-banking-net

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - clevertec-banking-net

networks:
  clevertec-banking-net:
    driver: bridge

volumes:
  db-data:
  pgadmin-data: