spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=${ACCOUNT_SERVICE_PATH}
          filters:
            - AuthenticationFilter

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=${CUSTOMER_SERVICE_PATH}
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=${AUTH_SERVICE_PATH}

  application:
    name: BANKING-GATEWAY

token:
  secret-key: ${JWT_SECRET}