spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/v1/accounts/**
          filters:
            - AuthenticationFilter  # Если оставляем фильтр в гэтвее, то для каждого секюрного сервиса

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - AuthenticationFilter  # Если оставляем фильтр в гэтвее, то для каждого секюрного сервиса

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**

  application:
    name: BANKING-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

token:
  secret-key: jk6a9Lnyy7wWJZubVG9Cf8QtQnL3U/ArPMVcHchXiOaFaPPygc99sM2LC25kscbu