spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_schema: @defaultSchema@
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    default-schema: @defaultSchema@
    liquibase-schema: @defaultSchema@
  datasource:
    url: jdbc:postgresql://localhost:@databasePort@/clevertec-banking?currentSchema=@defaultSchema@
    username: clevertec
    password: banking
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
#logging:
#  config: #мб уйдет в стартер