services:
  postgres:
    image: 'postgres:14.9'
    environment:
      - POSTGRES_DB=banking
      - POSTGRES_PASSWORD=antoha
      - POSTGRES_USER=antoha
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
