server:
  port: 8750
spring:
  application:
    name: ACCOUNT-CARD-SERVICE
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/account-card-service?currentSchema=account_card
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
    default-schema: account_card
    change-log: classpath:db/changelog/db.changelog-master.yaml
    liquibase-schema: account_card
  rabbitmq:
    addresses: amqp://admin:admin@localhost:5673
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
clevertec:
  rabbit:
    consumer:
      queue:
        account-queue: account_info
        card-queue: card-info
  feign:
    service:
      currency-client: "CURRENCY-SERVICE"
      currency-get-path: "/api/v1/currencies"

