spring:
  datasource:
    url: jdbc:postgresql://localhost:${PROD_DB_PORT:5432}/${PROD_DB_NAME:banking}?currentSchema=${PROD_DEFAULT_SCHEMA:account_card}
    username: ${PROD_DB_USERNAME:admin}
    password: ${PROD_DB_USERNAME:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
    default-schema: ${PROD_DEFAULT_SCHEMA:account_card}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    liquibase-schema: ${PROD_DEFAULT_SCHEMA:account_card}
  rabbitmq:
    addresses: amqp://${RABBIT_USERNAME:admin}:${RABBIT_PASSWORD:admin}@${PROD_RABBIT_HOST:localhost}:${PROD_RABBIT_PORT:5673}
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
clevertec:
  rabbit:
    consumer:
      queue:
        account-queue: ${PROD_ACCOUNT_QUEUE_NAME:account_info}
        card-queue: ${PROD_CARD_QUEUE_NAME:card-info}
  feign:
    service:
      currency-client: ${PROD_CURRENCY_SERVICE:CURRENCY-SERVICE}
      currency-get-path: ${PROD_CURRENCY_GET_PATH:/api/v1/currencies}
logging:
  level:
    org:
      hibernate:
        type: trace

eureka:
  client:
    service-url:
      defaultZone : http://${PROD_EUREKA_HOST:localhost}:${PROD_EUREKA_PORT:8761}/eureka/