services:
  postgres:
    image: 'postgres:14.9'
    environment:
      POSTGRES_USER: clevertec
      POSTGRES_PASSWORD: banking
      POSTGRES_DB: clevertec-banking
    ports:
      - "5432:5432"
    restart: always
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./rabbit/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./rabbit/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always