spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${PROD_DB_PORT}/${DB_NAME}?currentSchema=${DEFAULT_SCHEMA}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  liquibase:
    default-schema: ${DEFAULT_SCHEMA}
    change-log: db/changelog/db.changelog.yaml
    liquibase-schema: ${DEFAULT_SCHEMA}
  rabbitmq:
    port: ${PROD_RABBIT_PORT}
    host: ${PROD_RABBIT_HOST}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: ${DEFAULT_SCHEMA}
  data:
    redis:
      password: ${PROD_REDIS_PASSWORD}
      host: ${PROD_REDIS_HOST}
      port: ${PROD_REDIS_PORT}
      database: ${PROD_REDIS_DATABASE}
clevertec:
  feign:
    client:
      customer:
        name: CUSTOMER-SERVICE
        path: "/api/v1/customers"
  rabbit:
    queue:
      deposit: ${RABBIT_DEPOSIT_QUEUE}
eureka:
  client:
    service-url:
      defaultZone: http://${PROD_EUREKA_HOST}:${EUREKA_PORT}/eureka/