spring:
  datasource:
    url: jdbc:postgresql://${DEV_HOST_DB_URL}:${DEV_DB_PORT}/${DB_NAME}?currentSchema=${DEV_DEFAULT_SCHEMA}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  liquibase:
    enabled: true
    default-schema: ${DEFAULT_SCHEMA}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    liquibase-schema: ${DEFAULT_SCHEMA}
  rabbitmq:
    addresses: amqp://${RABBIT_USERNAME}:${RABBIT_PASSWORD}@${DEV_RABBIT_HOST}:${DEV_RABBIT_PORT}
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
clevertec:
  rabbit:
    consumer:
      queue:
        account-queue: ${DEV_ACCOUNT_QUEUE_NAME:account_info}
        card-queue: ${DEV_CARD_QUEUE_NAME:card-info}
  feign:
    service:
      currency-client: ${DEV_CURRENCY_SERVICE:CURRENCY-SERVICE}
      currency-get-path: ${DEV_CURRENCY_GET_PATH:/api/v1/currencies}
logging:
  level:
    org:
      hibernate:
        type: trace
eureka:
  client:
    service-url:
      defaultZone : http://${DEV_EUREKA_HOST:localhost}:${DEV_EUREKA_PORT:8761}/eureka/