server:
  port: 8751
spring:
  application:
    name: CREDIT-SERVICE
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/banking?currentSchema=credit
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
    default-schema: credit
    change-log: classpath:db/changelog/db.changelog-master.yaml
    liquibase-schema: credit
  rabbitmq:
    addresses: amqp://admin:admin@localhost:5673
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
clevertec:
  rabbit:
    consumer:
      queue:
        credit-queue: credit-details
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true