spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${PROD_DB_PORT:5432}/${DB_NAME:clevertec-banking}?currentSchema=${PROD_DEFAULT_SCHEMA:credit}
    username: ${PROD_DB_USERNAME:clevertec}
    password: ${PROD_DB_PASSWORD:banking}
  liquibase:
    enabled: true
    default-schema: ${PROD_DEFAULT_SCHEMA:credit}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    liquibase-schema: ${PROD_DEFAULT_SCHEMA:credit}
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
    port: ${PROD_RABBIT_PORT}
    host: ${PROD_RABBIT_HOST}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: ${PROD_DEFAULT_SCHEMA:credit}
    show-sql: true
clevertec:
  rabbit:
    consumer:
      queue:
        credit-queue: ${PROD_RABBITMQ_QUEUE_NAME:credit-details}
eureka:
  client:
    service-url:
      defaultZone: http://${PROD_EUREKA_HOST:localhost}:${PROD_EUREKA_PORT:8761}/eureka/
    enabled: true